---
title: "Joins, strings and dates"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)
```

## Joins

Create the data frame for animals

```{r}
animals <- tibble::tribble(
                ~location,   ~species,  ~maturity,
                 "lagoon",   "bobcat",    "adult",
                  "bluff",   "coyote", "juvenile",
                  "creek",      "fox",    "adult",
                   "oaks", "squirrel", "juvenile",
                  "bluff",   "bobcat",    "adult"
                )
)
```

Create the data frame for the locations

```{r}
sites <- tibble::tribble(
              ~location,      ~full_site_name, ~jurisdiction,
                "beach",       "Goleta Beach",     "SB City",
               "lagoon",        "UCSB Lagoon",        "UCSB",
                "bluff",       "Ellwood Mesa",     "SB City",
                 "oaks", "Fremont Campground",        "USFS"
              )

```

```{r}
sites_df <- data.frame(
  stringsAsFactors = FALSE,
          location = c("beach", "lagoon", "bluff", "oaks"),
                   full_site_name = c("Goleta Beach","UCSB Lagoon",
                                      "Ellwood Mesa","Fremont Campground"),
      jurisdiction = c("SB City", "UCSB", "SB City", "USFS")
               )
```

### Full join

Full join example

```{r}

full_join <- full_join(animals,sites, by = "location")

```

### Left Join

```{r}
left_join <- left_join(animals , sites, by = "location")
```

### Inner Join

```{r}
inner_join <- inner_join(animals , sites, by = "location")
```

```{r}

sites_2 <- sites |> 
  rename(loc= location)
```

Example of joining when key

```{r}
nonmatching <- full_join(animals, sites_2, by = c("location" = "loc"))
```

### Semi Join

```{r}
semi_join_example <- semi_join(animals, sites, by = "location")
```

### Anti join

```{r}
ani_join <- anti_join(animals, sites, by = "location")

```

## Task for penguins

```{r}
head(penguins)

penguins_island <- penguins |> 
  filter(island %in% c("Biscoe", "Dream")) |> 
  select (-year, -sex) |> 
  mutate(body_mass_kg = body_mass_g / 1000) |> 
  rename(location = island)
```

# Afternoon

## Dates and times with `lubridate`

Random Dates

```{r}
my_date <- "03-15-1998"
class(my_date)

lubridate::mdy(my_date)
my_date2 <- "11/07/2003"
lubridate::dmy(my_date2)

my_date3 <- "08-Jun-1974"
lubridate::dmy(my_date3)

my_date4 <- "19610518"
my_new_date4 <- lubridate::ymd(my_date4)

class(my_new_date4)
```

```{r}
lubridate::myd("08-2022-30")
```

```{r}
lubridate:: mdy("09/23/84")
```

### Now with date + time

```{r}
time <- "2022-08-12 11:18"
time <- ymd_hm(time)
time

class(time)
```

```{r}
bdy <- "06-08-93 06:40"
bday <- dmy_hm(bdy)
```

```{r}
with_tz(bday, "America/Mexico_City")
with_tz(bday, "Australia/Sydney")
with_tz(bday, "Pacific/Fiji")
```

```{r}
year(bday)
month(bday)
day(bday)
hour(bday)
minute(bday)
second(bday)
```

```{r}

teddy_bday <- lubridate::ymd("2017,06,15")
teddy_bday

wday(teddy_bday, label = TRUE)

wday(bday)
week(teddy_bday)
week(bday)
```

### Example of lubridate

```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_ymd <- urchin_counts |> 
  mutate( date = mdy(date)) |> 
  mutate(year = year(date),
         month = month(date),
         day = day(date))
```

```{r}

day_1 <- ymd("1993-08-06")
day_2 <- ymd("1990-10-08")

time_interval <- interval(day_1, day_2)

time_length(time_interval, "year,month")

year 
4.3596
```
